import { COLORS, DARKENED, ON_DARK, GRADIENTS, TYPOGRAPHY, BRAND } from '../data/brand.js';
import { cssGradient } from './gradients.js';

function colorEntries() {
  return [
    ...Object.entries(COLORS).map(([n, c]) => [n, c.hex]),
    ...Object.entries(DARKENED),
    ...Object.entries(ON_DARK),
  ];
}

const HEADER = `Nimiq design tokens — generated by nimiq-brand (source: @nimiq/style)`;

function toCss() {
  const lines = [`/* ${HEADER} */`, ':root {'];
  for (const [n, hex] of colorEntries()) lines.push(`  --${n}: ${hex};`);
  for (const [n, g] of Object.entries(GRADIENTS)) lines.push(`  --${n}-bg: ${cssGradient(g)};`);
  lines.push(`  --nimiq-font: ${TYPOGRAPHY.primaryFont.stack};`);
  lines.push(`  --nimiq-font-mono: '${TYPOGRAPHY.monospaceFont.family}', monospace;`);
  lines.push('}');
  return lines.join('\n');
}

function toScss() {
  const lines = [`// ${HEADER}`];
  for (const [n, hex] of colorEntries()) lines.push(`$${n}: ${hex};`);
  for (const [n, g] of Object.entries(GRADIENTS)) lines.push(`$${n}-bg: ${cssGradient(g)};`);
  return lines.join('\n');
}

function toJson() {
  return JSON.stringify({
    brand: BRAND,
    colors: Object.fromEntries(colorEntries()),
    gradients: Object.fromEntries(
      Object.entries(GRADIENTS).map(([n, g]) => [n, { ...g, css: cssGradient(g) }]),
    ),
    typography: TYPOGRAPHY,
  }, null, 2);
}

function toTailwind() {
  const colors = Object.fromEntries(
    colorEntries().map(([n, hex]) => [n.replace(/^nimiq-/, ''), hex]),
  );
  return [
    `// ${HEADER}`,
    '// Merge into tailwind.config.js → theme.extend',
    `export default ${JSON.stringify({
      colors: { nimiq: colors },
      fontFamily: { sans: ['Muli', 'sans-serif'], mono: ['Fira Mono', 'monospace'] },
    }, null, 2)};`,
  ].join('\n');
}

export function run(args, flags) {
  const format = flags.format || args[0] || 'css';
  const out = { css: toCss, scss: toScss, json: toJson, tailwind: toTailwind }[format];
  if (!out) {
    console.error(`Unknown format "${format}". Use: css, scss, json, tailwind.`);
    process.exitCode = 1;
    return;
  }
  console.log(out());
}
