// nq build-llms — render the LLM-native artifacts (llms.txt + llms-full.txt, llmstxt.org
// format) from the single source of truth (registry/index.json + registry/components/*/meta.json
// + assets/tokens.md). Invoked by scripts/sync-skill.mjs so the artifacts ride the same
// generate / --check cycle as registry/SKILL-BLOCK.md and can never drift from the registry.
//
// Deterministic by construction: no timestamps, no randomness — same inputs, byte-identical
// output. Components are grouped by category (categories sorted alphabetically, names sorted
// alphabetically within each), matching the SKILL-BLOCK.md ordering conventions.
import { readFile } from 'node:fs/promises';
import { join } from 'node:path';

const AUTOGEN = '<!-- AUTO-GENERATED by `nq sync-skill` from registry/index.json — do not hand-edit -->';

// Markdown-table cell: flatten newlines, escape pipes so prop text can't break the row.
const cell = v => (v === undefined || v === null || v === '' ? '-' : String(v))
  .replace(/\r?\n/g, ' ').replace(/\|/g, '\\|');

// Demote every heading in an embedded markdown file by one level (# -> ##, ## -> ###, ...)
// so it nests under this document's own H1 without colliding.
const demoteHeadings = md => md.replace(/^(#{1,5}) /gm, '#$1 ');

function componentBlock(meta) {
  const lines = [`#### ${meta.name}`, ''];

  const verify = meta.verified
    ? `pixel-verified, max diff ${meta.verify.maxDiffPct}% (viewport ${meta.verify.viewport.width}x${meta.verify.viewport.height}, selector \`${meta.verify.selector}\`)`
    : 'not pixel-verified (original brand composition, no upstream reference render)';
  lines.push(`Category: ${meta.category}. Variants: ${meta.variants.join(', ')}. Verification: ${verify}.`, '');

  lines.push(meta.purpose, '');

  if ((meta.props || []).length) {
    lines.push('| Prop | Type | Required | Default | Description |');
    lines.push('|---|---|---|---|---|');
    for (const p of meta.props) {
      lines.push(`| ${cell(p.name)} | ${cell(p.type)} | ${p.required ? 'yes' : 'no'} | ${cell(p.default)} | ${cell(p.description)} |`);
    }
  } else {
    lines.push('Props: none (class-based CSS component).');
  }
  lines.push('');

  const dep = (label, arr) => { if ((arr || []).length) lines.push(`- ${label}: ${arr.join(', ')}`); };
  dep('cssFiles', meta.cssFiles);
  dep('dependsOn', meta.dependsOn);
  dep('npmDeps', meta.npmDeps);
  dep('assetFiles', meta.assetFiles);
  if (meta.source) lines.push(`- source: ${meta.source.repo}@${meta.source.ref} (${(meta.source.files || []).join(', ')})`);
  lines.push('');

  if (meta.notes) lines.push(`Notes: ${meta.notes}`, '');
  return lines.join('\n');
}

export async function buildLlmsArtifacts(ROOT) {
  const index = JSON.parse(await readFile(join(ROOT, 'registry', 'index.json'), 'utf8'));
  const comps = index.components;
  const total = comps.length;
  const verifiedCount = comps.filter(c => c.verified).length;
  const unverified = comps.filter(c => !c.verified).map(c => c.name);
  const tokensMd = await readFile(join(ROOT, 'assets', 'tokens.md'), 'utf8');

  const metas = [];
  for (const c of comps) {
    metas.push(JSON.parse(await readFile(join(ROOT, 'registry', 'components', c.name, 'meta.json'), 'utf8')));
  }
  const byCat = {};
  for (const m of metas) (byCat[m.category] ??= []).push(m);
  const categories = Object.keys(byCat).sort();
  for (const cat of categories) byCat[cat].sort((a, b) => a.name.localeCompare(b.name, 'en'));

  const unverifiedNote = unverified.length
    ? ` The ${unverified.length === 1 ? 'entry' : 'entries'} not pixel-verified (${unverified.join(', ')}) ${unverified.length === 1 ? 'is an original brand composition' : 'are original brand compositions'} with no upstream reference render.`
    : '';

  // ---- llms.txt — discovery index ----
  const llms = `${AUTOGEN}
# nimiq-branding-cli

> Pixel-verified Nimiq component registry plus the \`nq\` CLI: scaffold ${total} Nimiq-branded UI components (${verifiedCount} pixel-diffed against renders of the real upstream source) into any project as Vue 3 SFCs or plain HTML/CSS, with the team's real asset library, a brand linter, and a weekly upstream drift audit.

Component data lives in \`registry/index.json\` (the index \`nq list\` reads) and \`registry/components/<name>/meta.json\` (props, CSS and asset dependencies, verify config, upstream source pins, porting notes). All paths below are relative to the repo root. This file and llms-full.txt are generated from the registry by \`nq sync-skill\`, so their contents cannot drift from the CLI.

## Full export

- [llms-full.txt](llms-full.txt): The whole registry as one flat markdown file: how to consume the CLI, the design-token tables, and every component with props, dependencies, source pins and verbatim porting notes. Start here to read everything at once.

## Docs

- [README.md](README.md): What the tool is, install steps, the full \`nq\` command surface, how pixel accuracy is enforced, repo layout.
- [PRINCIPLES.md](PRINCIPLES.md): The Nimiq design principles every component must come from; \`nq new\` embeds them as a 10-point checklist.
- [LINT.md](LINT.md): How \`nq lint\` renders a page and enforces the brand rules and breathability checks; errors fail, warnings advise.
- [AUDIT.md](AUDIT.md): The weekly self-learning audit that watches the live Nimiq upstreams for branding drift against the pinned registry.
- [FEATURES.md](FEATURES.md): Roadmap of multi-component features (flows and widgets) surveyed across Nimiq's apps and sites.

## Tokens and utilities

- [assets/tokens.md](assets/tokens.md): Design-token quick reference: modern oklch tokens, legacy nq-* hex values, the wallet text-opacity ladder, crypto colors, breakpoints.
- [references/utils.md](references/utils.md): @nimiq/utils API reference (formatting, validation, request links, tweening) verified against the published package.

## Registry

- [registry/index.json](registry/index.json): Machine-readable component index: name, purpose, category, variants and verified flag for all ${total} components.
- [upstream-pins.json](upstream-pins.json): The exact upstream commits the registry is verified against.

## Optional

- [NOTICE.md](NOTICE.md): Unofficial community project; brand-asset provenance and upstream licensing.
- [registry/SKILL-BLOCK.md](registry/SKILL-BLOCK.md): The generated summary block mirrored into the nimiq-ui agent skill.
`;

  // ---- llms-full.txt — the whole registry, flat ----
  const head = `${AUTOGEN}
# nimiq-branding-cli full reference

> The complete component registry of the nimiq-branding-cli in one flat markdown file: ${total} Nimiq UI components (${verifiedCount} pixel-diffed against renders of the verbatim upstream source), each with purpose, props, dependencies, upstream source pins and the porting notes that carry the traps. Generated from registry/index.json and registry/components/*/meta.json by \`nq sync-skill\`.

Every component ships as a Vue 3 SFC and/or a plain HTML/CSS snippet. "Pixel-verified" means the HTML demo is rendered headlessly (Playwright, 2x scale, fonts settled, animations disabled) and diffed with pixelmatch against a render of the real upstream component; the diff must stay under the component's max diff threshold.${unverifiedNote} Each component's notes field is reproduced verbatim below: it records the sample state, harness traps and deliberate deviations from upstream, and is the highest-value part of this file. Machine-readable siblings: \`registry/index.json\` (index), \`registry/components/<name>/meta.json\` (per-component detail), \`llms.txt\` (discovery index).

## How to consume

Copy components with the CLI instead of re-implementing them; \`nq add\` brings the component plus its dependencies, CSS and real assets.

\`\`\`
nq list                     # browse the registry (name, category, verified flag)
nq info <component>         # one component's purpose, props and CSS deps
nq init --style legacy      # drop Nimiq design tokens + base CSS into a project (or: modern)
nq add <component> --html   # copy a component into the project (or: --vue)
nq lint <file.html|url>     # enforce the brand rules on your own page
nq verify all               # (repo dev) re-run the pixel diffs against the references
\`\`\`

`;

  const tokensSection = demoteHeadings(tokensMd.trimEnd()) + '\n';

  const regHead = `
## Component registry

${total} components, ${verifiedCount} pixel-verified. Grouped by category (alphabetical), components alphabetical within each category.
`;

  const catSections = categories.map(cat =>
    `\n### ${cat}\n\n${byCat[cat].map(componentBlock).join('\n')}`).join('');

  const llmsFull = head + tokensSection + regHead + catSections;

  return [
    { rel: 'llms.txt', content: llms },
    { rel: 'llms-full.txt', content: llmsFull },
  ];
}
