#!/usr/bin/env python3
"""Extract the Mulish 700 glyph data that `nq lockup` lays out.

This is a BUILD-TIME script and the only Python in this repo. It runs once, and again only
if the Mulish font itself changes. `nq lockup` never calls it: the committed
assets/lockup/mulish-700.json is the artifact, and test/lockup.test.mjs proves that artifact
reproduces the shipped nimiq.kids lockup to four decimals. If that test passes, the JSON is
correct regardless of how it was produced.

Why the data is committed rather than read from the font at runtime:
  * the CLI stays pure Node with no font parsing and no new dependency
  * generation cannot drift between machines, font versions or shaping engines
  * fontkit, the obvious Node route, drops the cmap on a variation instance, so it cannot
    resolve a codepoint at wght=700 at all

Outlines are stored as command arrays rather than SVG path strings on purpose. SVGPathPen
emits H and V shortcuts, which carry a single coordinate, so a consumer transforming
"every pair of numbers" would corrupt them. BasePen also converts every quadratic to an
exactly equivalent cubic, so the consumer only ever sees M, L, C and Z with fixed arity.

Usage:  python3 scripts/gen-lockup-glyphs.py [path/to/mulish-variable.woff2]
Needs:  pip install fonttools brotli
"""

import json
import os
import sys

from fontTools.pens.basePen import BasePen
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

DEFAULT_FONT = os.path.expanduser(
    "~/gdkc/projects/nimiq.kids/public/fonts/mulish-latin-wght-normal.woff2"
)
# Lowercase is the fleet rule for a NIMIQ.<suffix>, but uppercase is needed too: nimiq.sale
# ships an uppercase SALE variant on the NIMIQ WALLET artwork, and outlineRun serves it.
CHARS = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789."
WEIGHT = 700
OUT = os.path.join(os.path.dirname(__file__), "..", "assets", "lockup", "mulish-700.json")


class JsonPen(BasePen):
    """Records absolute M / L / C / Z. BasePen turns TrueType quadratics into exact cubics."""

    def __init__(self, glyphSet):
        super().__init__(glyphSet)
        self.cmds = []

    def _moveTo(self, pt):
        self.cmds.append(["M", pt[0], pt[1]])

    def _lineTo(self, pt):
        self.cmds.append(["L", pt[0], pt[1]])

    def _curveToOne(self, p1, p2, p3):
        self.cmds.append(["C", p1[0], p1[1], p2[0], p2[1], p3[0], p3[1]])

    def _closePath(self):
        self.cmds.append(["Z"])


def main():
    path = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_FONT
    if not os.path.exists(path):
        sys.exit(f"font not found: {path}")

    font = instantiateVariableFont(TTFont(path), {"wght": WEIGHT}, inplace=True)
    glyphs = font.getGlyphSet()
    cmap = font.getBestCmap()
    upm = font["head"].unitsPerEm

    out = {
        "_comment": "GENERATED by scripts/gen-lockup-glyphs.py. Do not hand-edit.",
        "family": "Mulish",
        "weight": WEIGHT,
        "unitsPerEm": upm,
        "glyphs": {},
    }
    for ch in CHARS:
        if ord(ch) not in cmap:
            sys.exit(f"font has no glyph for {ch!r}")
        glyph = glyphs[cmap[ord(ch)]]
        pen = JsonPen(glyphs)
        glyph.draw(pen)
        # Round at the font's own precision. These are integer-ish design units; carrying
        # float noise into the JSON would show up as diff churn on every regeneration.
        cmds = [[c[0]] + [round(v, 4) for v in c[1:]] for c in pen.cmds]
        out["glyphs"][ch] = {"advance": glyph.width, "path": cmds}

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(os.path.normpath(OUT), "w") as fh:
        json.dump(out, fh, separators=(",", ":"))
        fh.write("\n")
    print(f"wrote {os.path.normpath(OUT)}  ({len(out['glyphs'])} glyphs at wght={WEIGHT})")


if __name__ == "__main__":
    main()
