// nq sync-skill — regenerate the nimiq-ui skill's registry block from the single
// source of truth (registry/index.json), so the skill can never drift from the CLI
// again (the "20 vs 40 components" class of bug).
//
// Writes the canonical generated block to registry/SKILL-BLOCK.md (committed, so CI
// can diff/verify it) AND, when the external skill file is present on this machine,
// patches the marked regions in place:
//   <!-- nq:summary:start --> ... <!-- nq:summary:end -->
//   <!-- nq:registry:start --> ... <!-- nq:registry:end -->
//
// Also regenerates the LLM-native artifacts at the repo root (llms.txt + llms-full.txt,
// llmstxt.org format) via scripts/build-llms.mjs, so they ride the same --check cycle.
//
// Skill path: $NIMIQ_UI_SKILL or ~/.claude/skills/nimiq-ui/SKILL.md
// Usage: node scripts/sync-skill.mjs [--check]   (--check: fail if anything is out of sync)
import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildLlmsArtifacts } from './build-llms.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');
const SKILL = process.env.NIMIQ_UI_SKILL || join(homedir(), '.claude', 'skills', 'nimiq-ui', 'SKILL.md');

const index = JSON.parse(await readFile(join(ROOT, 'registry', 'index.json'), 'utf8'));
const comps = index.components;
const total = comps.length;
const verified = comps.filter(c => c.verified).length;
const unverified = comps.filter(c => !c.verified).map(c => c.name);

// per-category, sorted; unverified flagged with *
const byCat = {};
for (const c of comps) (byCat[c.category] ??= []).push(c.name + (c.verified ? '' : '*'));
const catLines = Object.keys(byCat).sort()
  .map(cat => `**${cat}** ${byCat[cat].sort().join(', ')}`);

const AUTOGEN = '<!-- AUTO-GENERATED by `nq sync-skill` from registry/index.json — do not hand-edit -->';

const summaryBody = `${AUTOGEN}
The **nimiq-branding-cli** at \`~/Projects/nimiq/nimiq-branding-cli\` ships **${total} components** ported
from Nimiq's own Vue source, each **pixel-diffed against a verbatim upstream render** — **${verified} pixel-verified**,
plus ${total - verified} original brand composition (\`${unverified.join('`, `')}\`). If the registry has it, copying it in is strictly better than writing it.`;

const registryBody = `${AUTOGEN}
Registry (${total} components, ${verified} pixel-verified) ·
${catLines.join(' ·\n')}.
(\`*\` = unverified. \`flag-hex\` is an original brand composition, not an upstream port — battle-tested.)`;

// committed artifact for CI to diff
const artifact = `<!-- Generated by nq sync-skill. The nimiq-ui SKILL.md mirrors these two blocks. -->

## summary block
${summaryBody}

## registry block
${registryBody}
`;
const artifactPath = join(ROOT, 'registry', 'SKILL-BLOCK.md');
const prevArtifact = existsSync(artifactPath) ? await readFile(artifactPath, 'utf8') : '';
const artifactStale = prevArtifact !== artifact;
if (!CHECK) await writeFile(artifactPath, artifact);

// LLM-native artifacts at the repo root — generated from the same registry, checked the same way
const llmsFiles = await buildLlmsArtifacts(ROOT);
const llmsStale = [];
for (const f of llmsFiles) {
  const p = join(ROOT, f.rel);
  const prev = existsSync(p) ? await readFile(p, 'utf8') : '';
  if (prev !== f.content) llmsStale.push(f.rel);
  if (!CHECK) await writeFile(p, f.content);
}

function replaceRegion(text, key, body) {
  const re = new RegExp(`(<!-- nq:${key}:start -->)[\\s\\S]*?(<!-- nq:${key}:end -->)`);
  if (!re.test(text)) return { text, found: false };
  return { text: text.replace(re, `$1${body}\n$2`), found: true };
}

let skillStale = false, skillMsg = 'skill file not present (CI/headless) — wrote registry/SKILL-BLOCK.md only';
if (existsSync(SKILL)) {
  const orig = await readFile(SKILL, 'utf8');
  let out = orig;
  const r1 = replaceRegion(out, 'summary', summaryBody); out = r1.text;
  const r2 = replaceRegion(out, 'registry', registryBody); out = r2.text;
  const missing = [!r1.found && 'summary', !r2.found && 'registry'].filter(Boolean);
  skillStale = out !== orig;
  if (missing.length) skillMsg = `! markers missing in skill (${missing.join(', ')}) — add <!-- nq:<name>:start/end --> pairs`;
  else if (!CHECK) { await writeFile(SKILL, out); skillMsg = skillStale ? `patched ${SKILL}` : `${SKILL} already in sync`; }
  else skillMsg = skillStale ? `OUT OF SYNC: ${SKILL}` : `${SKILL} in sync`;
}

console.log(`nq sync-skill — ${total} components, ${verified} verified`);
console.log(`  artifact: registry/SKILL-BLOCK.md ${CHECK ? (artifactStale ? 'OUT OF SYNC' : 'in sync') : 'written'}`);
console.log(`  llms: ${llmsFiles.map(f => f.rel).join(' + ')} ${CHECK ? (llmsStale.length ? `OUT OF SYNC (${llmsStale.join(', ')})` : 'in sync') : 'written'}`);
console.log(`  ${skillMsg}`);

if (CHECK && (artifactStale || skillStale || llmsStale.length)) process.exitCode = 1;
